edit and consolidate the entire page of the Yen servers
gsbdarc/rcpedia pull request #45
Opened 2024-11-15 00:52 UTC by kevintran128

2024-11-19 20:11 UTC, natalya-patrikeeva requested changes
I have a few general comments. I think this page needs a lot more editing. 

Titles - consistent capitalization  (make every word capital for every ## level of header)

I think the section on how to connect should be at the top. The information about yen slurm also seems to cover most of the page but this is supposed to be “introduction to the yens” page so we can actually cut a lot of it. 

I would also move “Why use the yen servers” closer to the top and combine it with “introduction section”.  We can link to User Guide/Storage page here too. 

I think we can severely cut the slurm section as it is covered comprehensively - [here](https://rcpedia-dev.stanford.edu/_user_guide/slurm/)

I also don’t see the hardware description for yen1-5 nodes similar to yen-slurm nodes. We should probably also link to user limits page and link to slurm page but skip the detailed description of the slurm nodes.

2024-11-27 22:51 UTC, kevintran128 commented
Thank you for all your comments @natalya-patrikeeva . I revised accordingly. It should be good to go.

2024-12-02 15:39 UTC, natalya-patrikeeva commented on docs/_getting_started/yen-servers.md
> +![](/assets/images/yen-computing-infrastructure.png)
Let's add an alt name for the image

2024-12-02 15:39 UTC, natalya-patrikeeva commented on docs/_getting_started/yen-servers.md
>      Any work running on an interactive server (`yen[1-5]`) can only be started or stopped from that server.
bold face only for clarity

2024-12-03 00:37 UTC, kevintran128 commented
Resolved all comments in the 2nd batch @natalya-patrikeeva

2024-12-03 14:13 UTC, natalya-patrikeeva approved these changes
looks good

2024-12-03 17:17 UTC, merged