Added in more option, made terminal command links
gsbdarc/rcpedia pull request #80
Opened 2024-11-26 00:59 UTC by Jeffotter

2024-11-26 18:00 UTC, natalya-patrikeeva requested changes
formatting.

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +    See [this page](/_user_guide/best_practices_archive/?h=archive) to learn more about archiving your projects for long-term storage or transfer.
add new tab please

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
>  Perhaps one of the more common compression types, you can simply use `unzip`:
this sentence is not grammatically correct...

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
>  $ unzip bigfile.zip
remove $ from commands

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +Additional options for this command can be found [**here**](https://linuxize.com/post/how-to-unzip-files-in-linux/).
link needs a new tab

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +```title="Terminal Command"
no $

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +Additional options for this command and an explanation of the flags can be found [**here**](https://www.geeksforgeeks.org/tar-command-linux-examples/).
link

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +```title="Terminal Command"
no $

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +Additional options for this command can be found [**here**](https://www.geeksforgeeks.org/gunzip-command-in-linux-with-examples/).
link in a new tab

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +```title="Terminal Command"
no $

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
>  $ unrar e bigfile.rar
no $

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +```title="Terminal Command"
no $

2024-11-26 18:00 UTC, natalya-patrikeeva commented on docs/blog/posts/2023-08-18-how_to_uncompress.md
> +Additional options for this command can be found [**here**](https://itsfoss.com/use-7zip-ubuntu-linux/).
links in a new tab

2024-12-06 18:35 UTC, Jeffotter commented
Finished and pushed the changes

2024-12-10 16:14 UTC, natalya-patrikeeva requested changes
a few minor changes pls

2024-12-10 16:14 UTC, natalya-patrikeeva commented on docs/blog/posts/how_to_uncompress_large_files.md
> +
Let's capitalize title words, please

2024-12-10 16:14 UTC, natalya-patrikeeva commented on docs/blog/posts/how_to_uncompress_large_files.md
> +# How do I extract compressed files?
This can be the title but let's move it all the way up to the top of the page (and capitalize the words)

2024-12-10 16:14 UTC, natalya-patrikeeva commented on docs/blog/posts/how_to_uncompress_large_files.md
> +Large collections of files will often be compressed in order to make them more friendly for transfer or long-term storage. Below are examples on how to uncompress a few common compression file types
This paragraph can be combined with the previous one. They are saying the same thing.

2024-12-10 16:14 UTC, natalya-patrikeeva commented on docs/blog/posts/how_to_uncompress_large_files.md
> +Perhaps one of the more common compression types, you can simply use `unzip`:
this sentence is not grammatically correct...

2024-12-10 16:14 UTC, natalya-patrikeeva commented on docs/blog/posts/how_to_uncompress_large_files.md
> +tar -zxvf bigfile.tar.gz  # z: gzip, x: extract, v: verbose, f: file
let's remove # and everything after

2024-12-10 16:14 UTC, natalya-patrikeeva commented on docs/blog/posts/how_to_uncompress_large_files.md
> +tar -zxvf bigfile.tar.gz  # z: gzip, x: extract, v: verbose, f: file
We can put the comment and explanation before the command, inline with the text

2024-12-13 20:37 UTC, natalya-patrikeeva approved these changes
lgtm!

2024-12-13 21:23 UTC, merged