Added in interactive matlab page, modifed the yml
gsbdarc/rcpedia pull request #83
Opened 2024-11-26 03:27 UTC by Jeffotter

Im not too confident in my matlab knowlegde if anyone would like to add anything else into this one

2024-11-26 18:33 UTC, natalya-patrikeeva requested changes

2024-11-26 18:33 UTC, natalya-patrikeeva commented on docs/_user_guide/matlab_interactive.md
> +## Managing Matlab Software Libraries and Versions
that's not right. remove this paragraph

2024-12-16 21:27 UTC, Jeffotter commented on docs/_user_guide/matlab_interactive.md
> +matlab -nodesktop < hello_world.m
But this is for interactive yens?

2024-12-16 21:48 UTC, Jeffotter commented on docs/_user_guide/matlab_interactive.md
> +matlab -nodesktop < hello_world.m
Do we want to do JupyterHub in this?

2024-12-18 22:36 UTC, natalya-patrikeeva approved these changes
should be g2g

2024-12-18 22:41 UTC, merged